name: CI (build and test)

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]


jobs:
  tests:
    strategy:
      matrix:
        os: [ubuntu-22.04, macos-latest]
        python-version: ["3.9"]
    name: "Core, Python ${{ matrix.python-version }}, ${{ matrix.os }}"
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10

    steps:
      - uses: mamba-org/setup-micromamba@v1
        with:
          micromamba-version: '1.5.6-0' # any version from https://github.com/mamba-org/micromamba-releases
          environment-name: 'ilastik-tasks'
          create-args: >-
            --override-channels
            -c pytorch
            -c ilastik-forge 
            -c conda-forge python=${{ matrix.python-version }} ilastik 
            --no-channel-priority

      - name: Install package
        run: python -m pip install -e .[dev]

      - name: Regenerate the manifest
        run: python src/ilastik_tasks/dev/create_manifest.py

      - name: Check if manifest has changed
        run: |
          if [ -n "$(git diff --exit-code ./src/ilastik_tasks/__FRACTAL_MANIFEST__.json)" ]; then
          echo "__FRACTAL_MANIFEST__.json has changed. Please run 'python src/ilastik_tasks/dev/create_manifest.py' and commit the changes."
            exit 1
          else
            echo "__FRACTAL_MANIFEST__.json has not changed."
          fi

      - name: Test core library with pytest
        run: python -m pytest tests