name: CI (build and test)

on:
  push:
    branches:
      - main
    tags:
      - "*"
  pull_request:
  workflow_dispatch:
  release:
    types: [published]


jobs:
  tests:
    strategy:
      matrix:
        os: [ubuntu-22.04, macos-latest]
        python-version: ["3.11", "3.12", "3.13"]
    name: "Core, Python ${{ matrix.python-version }}, ${{ matrix.os }}"
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - uses: prefix-dev/setup-pixi@v0.8.9
        with:
          pixi-version: v0.50.2

      - name: Check if manifest has changed
        run: pixi run fractal-manifest check --package ilastik-tasks
        
      - name: Run tests
        run: pixi run -e dev pytest
  
  deploy:
    name: Deploy
    needs: tests
    if: success() && startsWith(github.ref, 'refs/tags/') && github.event_name != 'schedule'
    runs-on: ubuntu-latest

    permissions:
      # IMPORTANT: this permission is mandatory for trusted publishing on PyPi
      # see https://docs.pypi.org/trusted-publishers/
      id-token: write
      # This permission allows writing releases
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 🐍 Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Build
        run: |
          python -m pip install hatch hatch-vcs
          hatch build

      # This depends on conda packages not available on PyPI
      #- name: 🚢 Publish to PyPI
      # TODO remove the "if: false" line when the package is ready for pypi release
      #  if: false
      #  uses: pypa/gh-action-pypi-publish@release/v1

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          files: './dist/*'
